# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: config/samples.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
units: config/units.tsv

### ref config was disabled,but do not delete
### just copy your custome genome and annotaion to: resources/genome.fasta and resources/genome.gtf
ref:
  # Ensembl species name
  species: homo_sapiens
  # Ensembl release (make sure to take one where snpeff data is available, check 'snpEff databases' output)
  release: 100
  # Genome build
  build: GRCh38


trimming:
  activate: True

pca:
  activate: True
  labels:
    # columns of sample sheet to use for PCA
    - condition

diffexp:
  # contrasts for the deseq2 results method
  contrasts:
    wild-vs-mutated:
      - wild
      - mutated
  model: ~condition

# cutadapt params should be set if you'll trim the raw data (if not, it may cause errors in the following). Eg. "-q 20,20 --max-n 0.1 -m 75" 
# star: "--outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --sjdbGTFfile" has been set, and hence cannot be set here again
params:
  cutadapt-pe: ""
  cutadapt-se: ""
  star: ""
